{
  imports = [
    ./zsh.nix
    ./user-settings.nix
    ./system-settings.nix
    ./fhs.nix
    ./base-packages.nix
    ./extra-packages.nix
    ./legacy-packages.nix
    ./fonts.nix
    ./rice.nix
    ./sddm.nix
    ./sddm-avatar.nix
    #./music.nix
    ./postgres-docker.nix
    ./stylix.nix
    #./tmux.nix
  ];
}
