ipc = on
wallpaper {
    monitor = eDP-1
    path = /home/declan/.nixos/wall/berserk.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/declan/.nixos/wall/berserk.jpg
    fit_mode = cover
}
