declan-password: ENC[AES256_GCM,data:bPBTyHttrqIvyyynnej+gUiUJwRA1/dH6Feg+MGSVVhI7KQm6OiyL7njT2NFUWWL8ZDZzPbPdh78lcjdnfKanJSy84k1pqPksHuZwrpW0i1MUlFQ5iLsbhTbM0ziyenD0Ab6/wQ9ipWCDw==,iv:i2jlaXUbKcpE2K/KrYlBaZNEmWmn+EB+MY89/GdiEOc=,tag:SfF+Mm5ivnRMD/B8S8XoWg==,type:str]
root-password: ENC[AES256_GCM,data:EpDhnzplupQ8IvOUIz2eRDloJvqN7DfIgOWM9fnLfB7MPQyEmojdMO2umj0+uEUzttLgPB/O4TUzJHMvjHydhXkgKgDwZc9QDn75vbdiVdpbG4+a8LNv4JgcLnKqQz/V3mdFMy2fZg+vIQ==,iv:u/fPwB74bxzk14cTCUvnhi7+80IZV0hW9PsailZKgAc=,tag:K89S1D55fNJuqsOHex5cMg==,type:str]
sops:
    age:
        - recipient: age1e8py0g8rhflnf2t75suqenjmzvw0llg3agjgzmvzljcpz5fl8ycsxlu5r9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YVBkWDl6dXRpRXJmK21p
            d1hvVFd0SmFLbkJJeGpscXJ6cy80ZDNmSmxNCjVWQ2Rsc1MzaERyVzlKUVA4cE1H
            OTJJa1ZOOEFNaGdDVzBkZGlnODc1UDAKLS0tIHlZM3JWR0tEcm1Mb3daY3ludVhX
            M0JsZG52d1FPM2t3cGl1WURtTm9IUlUK8iEZEnElBf89G3B/QXpRhQRsVslumZi8
            kqIwCr8w8KE1YKDMT2uDDEqiaYVQvwA0qtiN3XS4xzBW/PNFnG0jyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T08:44:35Z"
    mac: ENC[AES256_GCM,data:xihYtdr9L3sG0sUcRDIXVqFNwH9WrOIqa3D8LDsiXItIAoNvMLnzBe1nu9CYPv93DSJIhFVCrDvwdCb1G9NAoOXDmBF1kUL1DB+9t0FWkLlJTWheEOMW4yLF2Tof38oBFEiDQN85f4P0cAkypMdJ9olbbaiMc4ZzzlVu2srXI8E=,iv:chzpp3LuFxU3NwkNAu211le3iguMiQ+KfXy8M5hKFEQ=,tag:RdbEAfQaxWvXQqTk/oKSVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
